export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
export const CURRENT_DATA = "CURRENT_DATA";
export const USER_LOCATION = "USER_LOCATION";
export const DARK_BUTTON = "DARK_BUTTON";
export const CELSIUS_BUTTON = "CELSIUS_BUTTON";
